server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka
spring:
  application:
    name: apartment-api-gateway
zuul:
  routes:
    user:
      path: /user-api/**
      serviceId: apartment-user-service