server:
  port: 0
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/apartment_db?useSSL=false
    username: root
    password: password1$
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
  application:
    name: apartment-user-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka
security:
  oauth2:
    client:
      grant-type: client_credentials
      clientId: userclient
      clientSecret: usersecret
      access-token-uri: http://localhost:7777/oauth/token
    resource:
      userInfoUri: http://localhost:7777/validateUser